# Generated by Django 3.1.3 on 2020-11-15 20:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('new_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_text',
            field=models.CharField(default=datetime.datetime(2020, 11, 15, 20, 42, 11, 790077, tzinfo=utc), max_length=200),
        ),
    ]
