# Generated by Django 3.1.3 on 2020-11-15 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('new_blog', '0002_auto_20201116_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 21, 3, 30, 747515, tzinfo=utc), verbose_name='date published'),
        ),
    ]
